language: java

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn clean verify

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh